# Base Image
FROM python:3.10-slim

# Install system dependencies (Tesseract OCR & OpenCV dependencies)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    glib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements and install python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Expose Streamlit default port
EXPOSE 8501

# Command to run Streamlit on Render
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]